packages:
  - packages/*
  - examples/*
  - apps/*
  - docs
  - utils

allowBuilds:
  esbuild: true
  msw: true
  sharp: true
  workerd: true

blockExoticSubdeps: true

catalog:
  '@biomejs/biome': 2.3.14
  '@types/mocha': ^10.0.10
  '@types/node': ^25.1.0
  '@types/react': ^19.2.7
  '@types/react-dom': ^19.2.3
  abitype: ^1.2.0
  mocha: ^11.7.4
  msw: 2.12.7
  ox: ^0.12.0
  typescript: 5.9.3
  viem: ^2.45.1
  wagmi: ^3.0.2
  zod: ^4.3.5

minimumReleaseAge: 2880

minimumReleaseAgeExclude:
  - iso-ledger
  - '@hugomrdias/docs'

trustPolicy: no-downgrade

trustPolicyExclude:
  - vite@6.4.1
  - chokidar@4.0.3
  - semver@6.3.1
  - undici-types@6.19.8
  - langium@3.3.1
  - reselect@5.1.1
