name: CI
on:
  push:
    branches:
      - master
    paths:
      - "packages/**"
      - .github/workflows/ci.yml
  pull_request:
    paths:
      - "packages/**"
      - .github/workflows/ci.yml
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
      - name: Use Node.js lts/*
        uses: actions/setup-node@v5
        with:
          node-version: lts/*
      - name: Install Dependencies
        run: pnpm install
      - name: Generate ABIs
        run: |
          pnpm -r --filter @filoz/synapse-core run generate-abi
          pnpm -r --filter @filoz/synapse-sdk run generate-abi
      - name: Check for ABI changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "Error: ABI generation resulted in changes. Please run 'pnpm run generate-abi' and commit the changes."
            git status
            git diff
            exit 1
          fi
      - name: Lint
        run: pnpm run lint
      - name: Build
        run: pnpm run build

  test-synapse-sdk:
    needs: lint
    strategy:
      fail-fast: false
      matrix:
        node: [lts/*, current]
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node }}
      - name: Playwright for Windows
        if: matrix.os == 'windows-latest'
        run: pnpx playwright install winldd
      - name: Install Dependencies
        run: pnpm install
      - name: Run synapse-sdk tests
        run: |
          pnpm config set script-shell bash
          pnpm -r --filter @filoz/synapse-sdk run test

  test-synapse-core:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
      - name: Use Node.js lts/*
        uses: actions/setup-node@v5
        with:
          node-version: lts/*
      - name: Install Dependencies
        run: pnpm install
      - name: Run synapse-core tests
        run: pnpm -r --filter @filoz/synapse-core run test
