name: release-please

on:
  push:
    branches:
      - master

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      paths_released: ${{ steps.release.outputs.paths_released }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          # PAT so release PRs trigger other workflows (auto-label, add-issues-and-prs-to-fs-project-board).
          # This PAT has the permissions outlined in https://github.com/googleapis/release-please-action?tab=readme-ov-file#workflow-permissions.
          # Using GITHUB_TOKEN suppresses follow-on workflow runs, which would mean release please PRs wouldn't get properly labeled and added to the project board.
          token: ${{ secrets.FILOZZY_RELEASE_PLEASE_PAT }}
          config-file: .github/release-please-config.json
          manifest-file: .github/release-please-manifest.json
  npm:
    needs: release
    if: |
      contains(fromJson(needs.release.outputs.paths_released), 'packages/synapse-sdk') || 
      contains(fromJson(needs.release.outputs.paths_released), 'packages/synapse-core') ||
      contains(fromJson(needs.release.outputs.paths_released), 'packages/synapse-react')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v6
      - uses: actions/setup-node@v6
        with:
          node-version: lts/*
          registry-url: "https://registry.npmjs.org"
      - run: pnpm install
      - run: pnpm run lint
      - run: pnpm run build
      - run: pnpm -r --filter './packages/**' publish --access=public
  docs:
    needs: release
    # Only publish docs if the synapse-sdk package is released (manual publish is possible from the GitHub UI)
    if: |
      contains(fromJson(needs.release.outputs.paths_released), 'packages/synapse-sdk')
    uses: ./.github/workflows/docs.yml
    secrets: inherit
