name: synapse-core
on:
  push:
    branches:
      - master
    paths:
      - "packages/synapse-core/**"
      - .github/workflows/synapse-core.yml
  pull_request:
    paths:
      - "packages/synapse-core/**"
      - .github/workflows/synapse-core.yml
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        node: [lts/*, current]
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node }}
      - name: Playwright for Windows
        if: matrix.os == 'windows-latest'
        run: pnpx playwright install winldd
      - name: Install Dependencies
        run: pnpm install
      # - name: Run tests
      #   run: pnpm -r --filter @filoz/synapse-core run test
      #   shell: bash
      - name: Check docs build
        run: pnpm -r --filter docs run build
